---
title: "p8105_HW_Joseph Kim"
author: "joseph Kim"
date: "10/9/2021"
output: github_document
---

##### Homework 2: Data Wrangling 

```{r setup}
library(tidyverse)
library(readxl)
```

## Read in Excel (Import dataset and datacleaning)

```{r}

trashwheel_df=
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel", range="A2:N535") %>%   
  janitor::clean_names() %>% 
  na.omit(dumpster) %>% 
  mutate(sports_balls=round(sports_balls,0)) 

```


```{r}

precipitation2018= 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>%
  na.omit() %>%
  mutate(year="2018") 
  
```


```{r}
precipitation2019= 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2019 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>%
  na.omit() %>%
  mutate(year="2019") 
```


```{r}
totalprecipitation2018_2019 = 
  rbind(precipitation2018, precipitation2019) %>%
  mutate(month = month.name[month])
```

Make sure to write the paragraph here.